### PR TITLE
Update GitHub Actions and drop unneeded steps

### PR DESCRIPTION
**Pull request by muzimuzhi**
To clear warnings thrown by a workflow run.
- current warnings https://github.com/gusbrs/zref-clever/actions/runs/4211065886
- effect (no warnings) of current PR https://github.com/muzimuzhi/zref-clever/actions/runs/4211127162

image

See commit messages for more info.

------

BTW, you may be interested in
- adding a dependabot to be noticed with new major releases of dependent actions
  - doc https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
  - usage in pgf https://github.com/pgf-tikz/pgf/blob/master/.github/dependabot.yml and texstudio https://github.com/texstudio-org/texstudio/blob/master/.github/dependabot.yml
- using an updated-weekly texlive docker image
  - https://gitlab.com/islandoftex/images/texlive
  - usage in pgf https://github.com/pgf-tikz/pgf/blob/dceb378b263061856b9a21082e5dc6fffdcdf494/.github/workflows/check.yml#L9

### CODE REVIEW

**Comment by gusbrs** [comment]
Oh!, I had been postponing dealing with those warnings. This is much welcome, thank you!

Can I ask a couple of things more regarding your other suggestions? About the dependabot, how does it work, you set up the file, declare the version you are using and, if there's a new major version you get an email warning? Is that it? If so, sounds good. 

About the Island of TeX docker images I've known of their existence for some time and I always wanted to investigate. I'm no guru in these matters, and I just looked around for what people were doing, and emulated it. And `siunitx` was a reference in this and other things. If I understand it well, the docker images would replace the need for https://github.com/zauguin/install-texlive, and also spare me from the pain of, every time I add a new dependency, cherry picking packages as they fail in the CI tests. Is this understanding correct? If so, it sounds good too. :smile:

**Comment by muzimuzhi** [comment]
> About the dependabot, how does it work, you set up the file, declare the version you are using and, if there's a new major version you get an email warning? Is that it? If so, sounds good.

For actions updates, it directly opens one PR per updated action. Currently it's not configurable to only send an email.

> If a more recent version of the action is available, Dependabot will send you a pull request that updates the reference in the workflow file to the latest version.
> https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot#about-dependabot-version-updates-for-actions

Examples
- https://github.com/pgf-tikz/pgf/pulls?q=is%3Apr+author%3Aapp%2Fdependabot (filtered by `author:app/dependabot`)

> If I understand it well, the docker images would replace the need for https://github.com/zauguin/install-texlive, and also spare me from the pain of, every time I add a new dependency, cherry picking packages as they fail in the CI tests. Is this understanding correct? If so, it sounds good too. 😄

Yes.

**Comment by gusbrs** [comment]
@muzimuzhi Thank you once again!

I'll definitely add the dependabot, and most likely use the IoT images. For the latter, I'll have to see if I can ensure the latest from `zref-check` and `zref-vario`, since I sometimes have to make coordinated releases between the three (I should probably make a bundle of them someday...). But I'll figure it out. Thanks!

**Comment by gusbrs** [comment]
@muzimuzhi As you see above, excellent tips! Appreciated! :heart:

**Comment by muzimuzhi** [comment]
> @muzimuzhi As you see above, excellent tips! Appreciated! ❤️

Just for future curious like me, here's a diff https://github.com/gusbrs/zref-clever/compare/1116b15..a543d0d, using GitHub's [two-dot git diff comparison](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-comparing-branches-in-pull-requests#two-dot-git-diff-comparison).

**Comment by gusbrs** [comment]
@muzimuzhi I've been reconsidering the use of the docker images for the purposes of CI tests, back to installing a basic TeX Live plus a set of packages. The docker images are pretty cool, the concept is "just right", but the tests have been taking about twice as much to run (from ~10min, which is already considerable, to ~20min). The difference does not seem to stem from initializing the container (which takes about 2min), it just "takes longer". I have no idea what the bottleneck might be. Is this difference in performance known? Do you happen to know if there are ways to improve things?

**Comment by muzimuzhi** [comment]
After a roughly skimming, nothing looks suspicious.

The [workflow runs](https://github.com/gusbrs/zref-clever/actions/workflows/main.yml) in current repo became slower since ~7 months ago, which seems to be the time when TeX Live 2023 released.

The workflow run triggered by pushing current HEAD https://github.com/gusbrs/zref-clever/commit/ddb9ed9c9f47b6baf72ec954fa71b5d7b74eda97 [took 21m 56s](https://github.com/gusbrs/zref-clever/actions/runs/6076675112) in current repo, while its neighbor run just succeeded using [only 16m 42s](https://github.com/muzimuzhi/zref-clever/actions/runs/6811313626) in my fork.

Can you rerun the workflow on current HEAD of this repo? If the existing run is too old to be rerun, pushing a new branch with no new commit should do the trick.

(Maybe it worth to continue the discussion in a new issue.)

**Comment by gusbrs** [comment]
@muzimuzhi Thank you for your comment.

TeX Live 2023 may be a cause. But I distinctly recall it taking considerably longer when I made the change, and this was made in February, some months before the new TeX Live.

But I'll make some tests about it. I've just triggered the workflow with a new push, which should give us the current state of things. I'll then (provisionally) restore the old workflow and test it too. Then I'll open a new issue with the results. You are right, it deserves one. ;-)

**Comment by gusbrs** [comment]
@muzimuzhi New issue opened (https://github.com/gusbrs/zref-clever/issues/20). As mentioned there, any thoughts are much appreciated.

**Pull request merged**
